const masterBank = {
  "biology": [
  {q: "The Genus into which man is classified is", a: "homo", options: ["chordata", "mammalia", "homo", "sapiens"]},
  {q: "Which of the following processes occurs in an organism before it becomes an adult?", a: "moulting", options: ["respiration", "locomotion", "moulting", "sensitivity"]},
  {q: "In a dicot leaf, the part that contains the phloem and xylem is known as the", a: "vascular bundle (midrib)", options: ["vein", "apex", "midrib", "petiole"]},
  {q: "The functions of vacuoles in plants are storage and", a: "support", options: ["protection", "strength", "support", "sensitivity"]},
  {q: "If plant cells are placed in a 6% salt solution (hypertonic), what would happen to the cell?", a: "it would become plasmolysed", options: ["turgid", "crenated", "haemolysed", "plasmolysed"]},
  {q: "How many molecules of oxygen are required for the aerobic respiration of three molecules of glucose?", a: "18", options: ["3", "6", "12", "18"]},
  {q: "Sclerenchyma tissues in plants are for", a: "mechanical support", options: ["water conduction", "mechanical support", "food storage", "food transport"]},
  {q: "The process by which a cell engulfs a bacterium is referred to as", a: "phagocytosis", options: ["phagocytosis", "pinocytosis", "endocytosis", "exocytosis"]},
  {q: "Which of the following statements is NOT correct about respiration in plants?", a: "light and chlorophyll must be present for it to occur", options: ["it occurs in all plant tissues", "light and chlorophyll must be present for it to occur", "energy is produced as the end product", "it occurs in the presence of oxygen"]},
  {q: "Urine in mammals is hypertonic compared to blood because", a: "much water has been reabsorbed from the renal tubules", options: ["urine contains high percentage of all cells", "all traces of sugar have been removed from urine", "urea is actively secreted into the renal tubules", "much water has been reabsorbed from the renal tubules"]},
  {q: "The naturally produced auxin in plants is", a: "indole acetic acid", options: ["indole acetic acid", "dichlorophenoxyacetic acid", "aldone", "florigen"]},
  {q: "The sympathetic nervous system causes", a: "constriction of the arteries", options: ["constriction of the arteries", "heartbeat to slow down", "increase in the secretion of saliva", "contraction of the bladder"]},
  {q: "Long sightedness (hypermetropia) could be corrected using a", a: "convex lens", options: ["biconvex lens", "convex lens", "biconcave lens", "concave lens"]},
  {q: "During the process of hearing in mammals, the structure in the middle ear which receives the first vibration is the", a: "malleus", options: ["oval window", "round window", "incus", "malleus"]},
  {q: "An important characteristic of fruits dispersed by water is the presence of", a: "fibrous covering", options: ["fibrous covering", "smooth surface", "water content", "pericarp"]},
  {q: "Plants which grow and produce fruits within a year are called", a: "annuals", options: ["annuals", "biennials", "perennials", "herbs"]},
  {q: "Chemical digestion in organisms is the", a: "breakdown of complex molecules into simple insoluble molecules", options: ["breakdown of starch into carbohydrates", "breakdown of complex molecules into simple molecules", "build up of simple insoluble molecules into complex insoluble molecules", "build up of simple soluble molecules into complex molecules"]},
  {q: "Excessive bleeding from an injury could be due to the lack of", a: "vitamin K", options: ["vitamin K", "vitamin E", "vitamin C", "vitamin B"]},
  {q: "Enzymatic digestion of protein begins in the", a: "stomach", options: ["mouth", "stomach", "small intestine", "large intestine"]},
  {q: "The parts of the human digestive system that secrete substances involved in the digestion of fats are the", a: "liver and pancreas", options: ["liver and pancreas", "stomach and liver", "pancreas and mouth", "mouth and stomach"]},
  {q: "If the small intestine of an animal does not have villi, the organism would have a problem with", a: "absorption of food", options: ["digestion of food", "absorption of water", "sorption of nutrients only", "absorption of food and nutrients"]},
  {q: "Which of the following statements is NOT correct about the dental formula of humans?", a: "three pairs of premolars are on the lower jaw", options: ["one pair of canines is on the upper jaw", "two pairs of premolars are on the lower jaw", "two pairs of incisors are on the lower jaw", "three pairs of molars are on the lower jaw"]},
  {q: "The relationship between a bee and a Tridax plant on a farmland is", a: "mutualism", options: ["competition", "predation", "mutualism", "epiphytism"]},
  {q: "The following ecological factors affect all habitat EXCEPT", a: "salinity", options: ["temperature", "humidity", "light", "salinity"]},
  {q: "An ecological instrument used to measure the transparency or turbidity of water is a", a: "Secchi disc", options: ["wind vane", "Six's thermometer", "Secchi disc", "hygrometer"]},
  {q: "When tilapias population in a pond reaches the carrying capacity, the population", a: "remains unchanged", options: ["alternately increases and decreases", "remains unchanged", "increases only", "decreases only"]},
  {q: "Which of the following statements about the pyramid of energy is correct?", a: "energy decreases from the base to the apex", options: ["energy remains constant across trophic levels", "energy decreases from the base to the apex", "energy increases from the base to the apex", "each trophic level is an independent energy source"]},
  {q: "Which of the following describes the term population?", a: "The number of organisms of the same species in a habitat", options: ["The number of fungi and snail on leaf litter", "The number of bees and butterflies on a flower", "The number of organisms of the same species in a habitat", "The number of roundworms in the gut of an animal"]},
  {q: "What is the population density of Ageratum sp. of frequency 1,850 on a land area measuring 100m²?", a: "18.50/m²", options: ["18.50/m²", "1.85/m²", "0.50/m²", "0.05/m²"]},
  {q: "Which of the following activities does NOT control pathogens?", a: "eating balanced diets", options: ["exposure to ultraviolet radiation", "use of disinfectants", "eating balanced diets", "destroying the habitats of pathogens"]},
  {q: "Which of the following diseases could be prevented by a BCG vaccination?", a: "tuberculosis", options: ["malaria", "cholera", "tuberculosis", "diphtheria"]},
  {q: "The main effect of deforestation is", a: "loss of soil particles", options: ["creation of new habitats", "loss of soil particles", "survival of more species", "reduction of carbon (IV) oxide in the atmosphere"]},
  {q: "Which of the following resources CANNOT be conserved?", a: "domestic wastes", options: ["mineral resources", "soil and water", "forest and wildlife", "domestic wastes"]},
  {q: "Which of the following activities is NOT suitable for forest conservation?", a: "felling of trees", options: ["felling of trees", "planting seedlings", "preventing bush fires", "planting tree crops"]},
  {q: "Which of the following pairs of features is an example of discontinuous variation?", a: "fingerprint and blood group", options: ["height and blood group", "height and sex", "colour and weight", "fingerprint and blood group"]},
  {q: "The ability of some individuals to taste phenylthiocarbamide is a", a: "physiological variation", options: ["morphological variation", "physiological variation", "morphological adaptation", "physiological adaptation"]},
  {q: "Alleles are found on", a: "chromosomes", options: ["nucleus", "nucleolus", "chromosomes", "tissues"]},
  {q: "A couple heterozygous for albino genes have normal skin colour. What is the probability that their child would be an albino?", a: "1/4", options: ["1/2", "1/3", "1/4", "1"]},
  {q: "If the percentage of adenine in the DNA of a human is 32%, what will be the percentage of thymine?", a: "32%", options: ["10%", "16%", "27%", "32%"]},
  {q: "Which of following statements is NOT correct about colour blindness?", a: "Females are not carriers", options: ["It is sex-linked trait", "Males are often carriers", "Females are not carriers", "The trait is controlled by a recessive gene"]},
  {q: "Lamarck's theory of evolution states that", a: "organisms transfer acquired characters to their offspring", options: ["characteristics of organisms are not the sum of the characters of their parents", "characteristics of organisms are determined by mutation", "organisms transfer acquired characters to their offspring", "organism acquire genes from their parents"]},
  {q: "The castes of the organisms found in a beehive are", a: "drones, queen and workers", options: ["drones, queen and workers", "workers, soldiers and reproductives", "soldiers, workers and king", "king, queen and soldiers"]},
  {q: "The theory of natural selection in evolution was formulated by", a: "Charles Darwin", options: ["Mathias Schleiden", "Louis Pasteur", "Charles Darwin", "Jean Lamarck"]},
  {q: "Species are groups of organisms that", a: "can interbreed freely", options: ["are of different origins and symbols", "are found in the same habitat", "cannot interbreed freely", "can interbreed freely"]},
  {q: "A plant with short, thick, vertical underground stem is a", a: "corm", options: ["rhizome", "bulb", "corm", "tuber"]},
  {q: "Which of the following organisms consists of unicellular cells joined to form a filament?", a: "Spirogyra", options: ["Amoeba", "Spirogyra", "Euglena", "Chlamydomonas"]},
  {q: "The structure in the cell that controls the movement of substances in and out of the cell is the", a: "plasma membrane", options: ["cytoplasmic membrane", "nuclear membrane", "protoplasm", "endoplasm"]},
  {q: "The bursting of a red blood cell placed in a hypotonic solution is called", a: "haemolysis", options: ["plasmolysis", "haemolysis", "crenation", "cytolysis"]},
  {q: "The function of the root hair in plants is to", a: "absorb soil water by osmosis", options: ["absorb soil water by osmosis", "excrete water and mineral salts", "purify the soil for the plant", "translocate manufactured food"]},
  {q: "If a germinating seed is attached horizontally to a revolving klinostat, what would be the effect on the seedling after three days?", a: "the radicle will grow horizontally", options: ["the plumule will curve vertically upward", "the radicle will curve towards the ground", "the plumule and radicle will grow vertically upwards", "the radicle will grow horizontally"]},
  {q: "Filtrates in the Bowman's capsule contain vitamins because", a: "they are soluble", options: ["they have low molecular weight", "most of them are soluble", "they cannot be reabsorbed into the blood", "little amount is required by the body"]},
  {q: "The structures that contain grey matter and white matter are found in the", a: "nervous system", options: ["reproductive system", "nervous system", "respiratory system", "digestive system"]},
  {q: "The part that protects the organ is labelled as", a: "sclera", options: ["iris", "pupil", "sclera", "cornea"]},
  {q: "The condition necessary for pollination to occur between plants P and Q should be", a: "A. of the same species", options: ["A. of the same species", "B. brightly coloured", "C. well scented", "D. of different species"]},
  {q: "The agent of dispersal of the Parachute-like tuft of hairs is", a: "wind", options: ["animal", "explosive mechanism", "water", "wind"]},
  {q: "Which of the following does NOT occur in the light reaction of photosynthesis?", a: "Carbon (IV) oxide combines with hydrogen", options: ["Chlorophyll absorbs sunlight", "Carbon (IV) oxide combines with hydrogen", "Water occurs", "Hydroxyl ions are produced"]},
  {q: "The rate of photosynthesis in a wilted herbaceous plant is reduced because", a: "stomata are closed", options: ["enzymes in the leaf were denatured", "chlorophyll amount reduced", "stomata are closed", "amount of carbon dioxide decreased"]},
  {q: "The element required for chlorophyll formation in plants is", a: "magnesium", options: ["iron", "calcium", "phosphorus", "magnesium"]},
  {q: "The process of food digestion in mammals would", a: "make energy immediately available to the body", options: ["make energy immediately available to the body", "promote growth and repair of tissues", "provide sufficient food materials within the body", "render food substances soluble and absorbable"]},
  {q: "Which of the following food substances would give a negative reaction with Benedict's reagent?", a: "Sucrose", options: ["Fructose", "Glucose", "Galactose", "Sucrose"]},
  {q: "Sunlight is the major source of", a: "vitamin D", options: ["vitamin A", "vitamin B", "vitamin C", "vitamin D"]},
  {q: "The pathway through which nutrients are replenished and circulated in an ecosystem is called a", a: "nutrient cycle", options: ["food chain", "nutrient cycle", "pyramid of numbers", "food web"]},
  {q: "The following is a food chain: Grasses -> Grasshoppers -> Lizards -> Hawks. Which statement is correct?", a: "lizards eaten by hawks is greater than the number of hawks", options: ["grasses eaten by grasshoppers is fewer than the number of grasshoppers", "grasses eaten by grasshoppers is greater than the number of grasshoppers", "lizards eaten by hawks is greater than the number of hawks", "hawks is greater than the number of lizards"]},
  {q: "Which of the following gases is released during the decomposition of organic matter?", a: "Carbon (IV) oxide", options: ["Carbon (IV) oxide", "Sulphur (IV) oxide", "Hydrogen sulphide", "Nitrous oxide"]},
  {q: "An environmental problem caused by Sulphur (IV) oxide is", a: "acid rain", options: ["acid rain", "deforestation", "global warming", "erosion"]},
  {q: "The phenomenon by which a farmland is left to fallow for several years develops into a forest is called", a: "succession", options: ["succession", "afforestation", "colonization", "deforestation"]},
  {q: "The source of energy that is mostly likely to lead to pollution in the community is", a: "coal", options: ["solar", "kerosene", "coal", "wind"]},
  {q: "Which of the following traits is NOT heritable?", a: "Ability to roll the tongue", options: ["Ability to roll the tongue", "Taste PTC", "Blood group", "None of the above"]},
  {q: "A woman with blood group A gives birth to a child with blood group O. Which of the following blood groups cannot belong to the father?", a: "AB", options: ["A", "B", "AB", "O"]},
  {q: "Which of the following statements is correct about the cross? (Aa x Aa)", options: ["all offspring are heterozygous", "both parents are homozygous", "the female is homozygous", "both parents are heterozygous"], a: "both parents are heterozygous"},
  {q: "The physical appearance of an organism is described as its", a: "phenotype", options: ["phenotype", "genotype", "allele", "chromosome"]},
  {q: "Mutation leads to evolution because it", a: "gives rise to new individuals that differ from their parents", options: ["kills all organisms where it occurs", "does not confer adaptability to the offspring", "gives rise to new individuals that differ from their parents", "bear genes for inheritance in plants"]},
  {q: "Which type of breeding is represented by industrial melanism in peppered moths?", a: "Natural selection", options: ["Artificial selection", "Natural selection", "Inbreeding", "Out-breeding"]},
  {q: "The growth process that would occur in an organism before it becomes an adult is", a: "moulting", options: ["respiration", "locomotion", "moulting", "sensitivity"]},
  {q: "The part of a leaf that contains the phloem and xylem is the", a: "midrib", options: ["vein", "apex", "midrib", "petiole"]},
  {q: "The functions of vacuoles in plants are", a: "storage and support", options: ["protection", "strength", "support", "storage and support"]},
  {q: "If plant cells are placed in a 6% salt solution (hypertonic), what would happen to the cell?", a: "it would become plasmolysed", options: ["turgid", "crenated", "haemolysed", "plasmolysed"]},
  {q: "How many molecules of oxygen are required for the aerobic respiration of three molecules of glucose?", a: "18", options: ["3", "6", "12", "18"]},
  {q: "Sclerenchyma tissues in plants are for", a: "mechanical support", options: ["water conduction", "mechanical support", "food storage", "food transport"]},
  {q: "The process by which a cell engulfs a bacterium is referred to as", a: "phagocytosis", options: ["phagocytosis", "pinocytosis", "endocytosis", "exocytosis"]},
  {q: "The biological system that carries out the illustrated biological process in humans is the", a: "circulatory system", options: ["respiratory", "circulatory", "respiratory", "nervous"]},
  {q: "Which of the following statements is NOT correct about respiration in plants?", a: "it occurs only in the presence of light", options: ["it occurs in all plant tissues", "it occurs only in the presence of light", "energy is produced as the end product", "it occurs in the presence of oxygen"]},
  {q: "Urine is hypertonic compared to blood because", a: "much water has been reabsorbed from the renal tubules", options: ["urine contains high percentage of all cells", "all traces of sugar have been removed from urine", "urea is actively secreted into the renal tubules", "much water has been reabsorbed from the renal tubules"]},
  {q: "The naturally produced auxin in plants is", a: "Indole Acetic Acid", options: ["Indole Acetic Acid", "dichlorophenoxyacetic acid", "aldone", "florigen"]},
  {q: "The sympathetic nervous system causes", a: "constriction of the arteries", options: ["constriction of the arteries", "heartbeat to slow down", "increase in the secretion of saliva", "contraction of the bladder"]},
  {q: "Long-sightedness (hypermetropia) is corrected with convex (converging) lens because the", a: "eyeball is too short", options: ["eyeball is too short", "lens is too thick", "eyeball is too long", "lens is too weak"]},
  {q: "The malleus is the first bone in the middle ear that receives vibrations from the", a: "eardrum", options: ["oval window", "round window", "stapes", "eardrum"]},
  {q: "Fruits dispersed by water typically have a", a: "fibrous covering", options: ["fibrous covering", "smooth surface", "water content", "pericarp"]},
  {q: "Plants that complete their life cycle within a year are known as", a: "annuals", options: ["annuals", "biennials", "perennials", "herbs"]},
  {q: "Chemical digestion involves the breakdown of complex molecules into", a: "simpler molecules", options: ["insoluble molecules", "carbohydrates", "simpler molecules", "complex insoluble molecules"]},
  {q: "Vitamin K is essential for blood clotting. A deficiency in vitamin K can result in", a: "excessive bleeding", options: ["excessive bleeding", "night blindness", "scurvy", "rickets"]},
  {q: "The digestion of protein begins in the stomach where", a: "pepsin breaks down proteins", options: ["pepsin breaks down proteins", "ptyalin breaks down starch", "lipase breaks down fats", "amylase breaks down sugar"]},
  {q: "The liver produces bile, which aids in the", a: "emulsification of fats", options: ["digestion of proteins", "emulsification of fats", "absorption of vitamins", "digestion of carbohydrates"]},
  {q: "The villi in the small intestine are essential for", a: "nutrient absorption", options: ["food digestion", "nutrient absorption", "water excretion", "enzyme production"]},
  {q: "Which of the following statements is NOT correct about the dental formula of humans?", a: "two pairs of molars are on the upper jaw", options: ["two pairs of incisors are on the lower jaw", "one pair of canines is on the upper jaw", "two pairs of molars are on the upper jaw", "three pairs of molars on the lower jaw"]},
  {q: "The relationship between a bee and a Tridax plant on a farmland is", a: "mutualism", options: ["competition", "predation", "mutualism", "epiphytism"]},
  {q: "The following ecological factors affect all habitats EXCEPT", a: "salinity", options: ["temperature", "humidity", "light", "salinity"]},
  {q: "A Secchi disc is a circular plate used in an aquatic habitat as an indicator of", a: "water clarity", options: ["water temperature", "water depth", "water clarity", "water pressure"]},
  {q: "Carrying capacity is the maximum number of individuals that an environment can", a: "support sustainably", options: ["produce in a year", "support sustainably", "lose to predators", "export to other habitats"]},
  {q: "The pyramid of energy represents the flow of energy through an ecosystem. At each trophic level, energy is", a: "lost as heat", options: ["increased", "lost as heat", "remains constant", "stored completely"]},
  {q: "Eutrophication is the process in which a body of water becomes enriched with", a: "nutrients like nitrates", options: ["oxygen", "nutrients like nitrates", "salt", "heavy metals"]},
  {q: "A population refers to all individuals of a single species in a specific area at a", a: "given time", options: ["given time", "given habitat", "given altitude", "given temperature"]},
  {q: "Population density is calculated by dividing the total number of individuals by the", a: "area they inhabit", options: ["amount of food", "area they inhabit", "number of predators", "total birth rate"]},
  {q: "Eating a balanced diet is important for maintaining general health and", a: "supporting the immune system", options: ["increasing body weight", "supporting the immune system", "reducing water intake", "preventing genetic mutations"]},
  {q: "BCG (Bacillus Calmette-Guérin) is a vaccine specifically developed to prevent", a: "tuberculosis", options: ["malaria", "cholera", "diphtheria", "tuberculosis"]},
  {q: "Deforestation leads to the loss of fertile topsoil, which can lead to", a: "long-term degradation of the land", options: ["increased biodiversity", "long-term degradation of the land", "faster forest growth", "lower carbon dioxide levels"]},
  {q: "Domestic wastes are by-products of human activities and are NOT conserved because they are", a: "managed or recycled", options: ["valuable natural resources", "managed or recycled", "infinite in supply", "essential for plant growth"]},
  {q: "The felling of trees is not suitable for forest conservation because it", a: "negatively impacts biodiversity", options: ["helps soil erosion", "negatively impacts biodiversity", "increases tree cover", "promotes sustainable management"]},
  {q: "Sex, fingerprint and blood group are examples of", a: "discontinuous variation", options: ["continuous variation", "discontinuous variation", "environmental variation", "morphological adaptation"]},
  {q: "Which of the following organisms contains chlorophyll in its cells?", a: "Euglena", options: ["Caterpillar", "Paramecium", "Euglena", "Grasshopper"]},
  {q: "Species are groups of organisms that", a: "can interbreed freely", options: ["are of different origins", "are found in the same habitat", "cannot interbreed freely", "can interbreed freely"]},
  {q: "A plant with short, thick, vertical underground stem is a", a: "corm", options: ["rhizome", "bulb", "corm", "tuber"]},
  {q: "The type of reproduction illustrated in Amoeba is", a: "binary fission", options: ["budding", "binary fission", "grafting", "vegetative propagation"]},
  {q: "Which of the following organisms consists of unicellular cells joined to form a filament?", a: "Spirogyra", options: ["Spirogyra", "Euglena", "Chlamydomonas", "Amoeba"]},
  {q: "The structure in the cell that controls the movement of substances in and out of the cell is the", a: "plasma membrane", options: ["cytoplasmic membrane", "nuclear membrane", "protoplasm", "endoplasm"]},
  {q: "The bursting of a red blood cell placed in a hypotonic solution is called", a: "haemolysis", options: ["plasmolysis", "haemolysis", "crenation", "cytolysis"]},
  {q: "The function of the root hair in plants is to", a: "absorb soil water by osmosis", options: ["absorb soil water by osmosis", "excrete water and mineral salts", "purify the soil for the plant", "translocate manufactured food"]},
  {q: "If a germinating seed is attached horizontally to a revolving klinostat, the", a: "radicle will grow horizontally", options: ["plumule will curve vertically upward", "radicle will curve towards the ground", "plumule and radicle will not show curvature", "radicle will curve vertically upwards"]},
  {q: "Filtrates in the Bowman's capsule contain vitamins because they", a: "are soluble", options: ["have low molecular weight", "are soluble", "cannot be reabsorbed into the blood", "are required by the body"]},
  {q: "The structures that contain grey matter and white matter are found in the", a: "nervous system", options: ["reproductive system", "nervous system", "respiratory system", "digestive system"]},
  {q: "The condition necessary for pollination to occur between plants P and Q should be", a: "of the same species", options: ["of the same species", "brightly coloured", "well scented", "of different species"]},
  {q: "The agent of dispersal of the fruit with a parachute-like tuft of hairs is", a: "wind", options: ["animal", "explosive mechanism", "water", "wind"]},
  {q: "Which of the following does not occur in the light reaction of photosynthesis?", a: "CO2 combines with hydrogen", options: ["Chlorophyll absorbs sunlight", "CO2 combines with hydrogen", "Water occurs", "Hydroxyl ions are produced"]},
  {q: "The rate of photosynthesis in a wilted herbaceous plant is reduced because", a: "stomata are closed", options: ["enzymes in the leaf were denatured", "chlorophyll amount reduced", "stomata are closed", "CO2 amount decreased"]},
  {q: "The element required for chlorophyll formation in plants is", a: "magnesium", options: ["iron", "calcium", "phosphorus", "magnesium"]},
  {q: "The process of food digestion in mammals would", a: "render food substances soluble", options: ["make energy immediately available", "promote growth and repair", "provide sufficient food materials", "render food substances soluble"]},
  {q: "Which of the following food substances would give a negative reaction with Benedict's reagent?", a: "Sucrose", options: ["Fructose", "Glucose", "Galactose", "Sucrose"]},
  {q: "Sunlight is the major source of", a: "vitamin D", options: ["vitamin A", "vitamin B", "vitamin C", "vitamin D"]},
  {q: "The pathway through which nutrients are replenished and circulated in an ecosystem is called a", a: "nutrient cycle", options: ["food chain", "nutrient cycle", "pyramid of energy", "food web"]},
  {q: "Which of the following ecological problems is caused by Sulphur (IV) oxide?", a: "Acid rain", options: ["Acid rain", "Deforestation", "Global warming", "Erosion"]},
  {q: "The phenomenon by which a farmland is left to fallow for several years develops into a forest is called", a: "succession", options: ["succession", "afforestation", "colonization", "deforestation"]},
  {q: "A farmer planted many seeds on a small piece of land. The plants that germinated were likely to experience", a: "competition", options: ["mutualism", "competition", "predation", "commensalism"]},
  {q: "Which of the following effects would not be observed among the population of the plants?", a: "Rise in disease conditions", options: ["Rise in disease conditions", "Death", "Mutualistic relationship", "Competition"]},
  {q: "The source of energy that is mostly likely to lead to pollution in the community is", a: "coal", options: ["solar", "kerosene", "coal", "wind"]},
  {q: "The two sources of energy that would mostly lead to pollution in the community are", a: "solar and kerosene", options: ["solar and kerosene", "coal, kerosene and coal", "solar and wind", "coal and wind"]},
  {q: "Which of the following traits is not heritable?", a: "Ability to roll the tongue", options: ["Ability to roll the tongue", "Taste PTC", "Blood group", "None of the above"]},
  {q: "A woman with blood group A gives birth to a child with blood group O. Which of the following blood groups cannot belong to the father?", a: "AB", options: ["A", "B", "AB", "O"]},
  {q: "The physical appearance of an organism is described as its", a: "phenotype", options: ["phenotype", "genotype", "allele", "chromosome"]},
  {q: "Mutation leads to evolution because it", a: "gives rise to new individuals", options: ["kills all organisms where it occurs", "does not confer adaptability", "gives rise to new individuals", "bears genes for inheritance"]},
  {q: "Which type of breeding is represented by industrial melanism in peppered moths?", a: "Natural selection", options: ["Artificial selection", "Natural selection", "Inbreeding", "Out-breeding"]},
  {q: "In a test, a student paired some scientists with their famous work as shown below. Which of the following pairings is not correct?", a: "Schleiden and Schwann -> natural selection", options: ["Charles Darwin -> preservation of food", "Gregor Mendel -> natural selection", "Jean Baptiste -> inheritance of acquired characters", "Schleiden and Schwann -> natural selection"]},
  {q: "The theory of natural selection in evolution was formulated by", a: "Charles Darwin", options: ["Mathias Schleiden", "Louis Pasteur", "Charles Darwin", "Jean Lamarck"]},
  {q: "The ability of some individuals to taste phenylthiocarbamide is a", a: "physiological variation", options: ["morphological variation", "physiological variation", "morphological adaptation", "physiological adaptation"]},
  {q: "Alleles are found on", a: "chromosomes", options: ["nucleus", "nucleolus", "chromosomes", "tissues"]},
  {q: "A couple heterozygous for albino genes have normal skin colour. What is the probability that their child would be an albino?", a: "1/4", options: ["1/2", "1/3", "1/4", "1"]}
],
  "physics": [
  /* --- Specific Heat Capacity (SHC) --- */
  {q: "A 500g copper block at 80 °C is placed in 1kg of water at 20 °C. Calculate the final equilibrium temperature. [SHC of copper = 400 Jkg⁻¹K⁻¹, water = 4200 Jkg⁻¹K⁻¹]", a: "22.7 °C", options: ["21.5 °C", "22.7 °C", "25.0 °C", "30.2 °C"]},
  {q: "An electric heater rated 1.5 kW takes 4 minutes to heat 2.5 kg of a liquid from 25 °C to 75 °C. Calculate the specific heat capacity of the liquid.", a: "2880 Jkg⁻¹K⁻¹", options: ["2100 Jkg⁻¹K⁻¹", "2500 Jkg⁻¹K⁻¹", "2880 Jkg⁻¹K⁻¹", "3200 Jkg⁻¹K⁻¹"]},
  {q: "Calculate the heat capacity of a lead piece of mass 250g. [Specific heat capacity of lead = 130 Jkg⁻¹K⁻¹]", a: "32.5 JK⁻¹", options: ["13.0 JK⁻¹", "32.5 JK⁻¹", "52.0 JK⁻¹", "65.0 JK⁻¹"]},
  {q: "A piece of iron of mass 2 kg falls from a height of 50m. If all its potential energy is converted into heat in the iron, calculate the rise in temperature. [SHC of iron = 460 Jkg⁻¹K⁻¹, g = 10 ms⁻²]", a: "1.09 °C", options: ["0.54 °C", "1.09 °C", "2.18 °C", "4.35 °C"]},
  {q: "Two liquids X and Y have mass ratio 2:3 and specific heat capacity ratio 3:4. If the same amount of heat is supplied to both, calculate the ratio of their temperature rise.", a: "2:1", options: ["1:2", "2:1", "1:1", "3:2"]},
  {q: "A projectile is fired with a velocity of 100 ms⁻¹ at an angle of 30° to the horizontal. Calculate the time it takes to reach the maximum height. [g = 10 ms⁻²]", a: "5.0 s", options: ["2.5 s", "5.0 s", "8.6 s", "10.0 s"]},
  {q: "A car of mass 800 kg moving at 30 ms⁻¹ is brought to rest in 15 s by a constant braking force. Calculate the distance covered before coming to rest.", a: "225 m", options: ["112.5 m", "225 m", "450 m", "600 m"]},
  {q: "A capacitor of 8 μF is charged to 100 V and then connected in parallel to an uncharged 12 μF capacitor. Calculate the final potential difference.", a: "40 V", options: ["20 V", "40 V", "60 V", "80 V"]},
  {q: "Calculate the energy required to convert 2 kg of ice at 0 °C to water at 10 °C. [Specific latent heat of fusion = 3.36 × 10⁵ Jkg⁻¹, Specific heat capacity of water = 4200 Jkg⁻¹K⁻¹]", a: "756,000 J", options: ["672,000 J", "756,000 J", "840,000 J", "912,000 J"]},
  {q: "An object is placed 20 cm from a converging lens of focal length 15 cm. Calculate the magnification of the image formed.", a: "3.0", options: ["1.5", "2.0", "3.0", "4.0"]},
  {q: "A radio station broadcasts at a frequency of 90 MHz. If the speed of light is 3.0 × 10⁸ ms⁻¹, calculate the wavelength of the waves.", a: "3.33 m", options: ["0.33 m", "2.70 m", "3.33 m", "30.0 m"]},
  {q: "A man of mass 70 kg runs up a flight of stairs 5 m high in 4 s. Calculate his power output. [g = 10 ms⁻²]", a: "875 W", options: ["350 W", "700 W", "875 W", "1400 W"]},
  {q: "A wire of length 4.0 m and diameter 2.0 mm has a resistance of 0.5 Ω. Calculate the resistivity of the material.", a: "3.93 × 10⁻⁷ Ωm", options: ["1.57 × 10⁻⁷ Ωm", "3.93 × 10⁻⁷ Ωm", "7.86 × 10⁻⁷ Ωm", "1.24 × 10⁻⁶ Ωm"]},
  {q: "An AC circuit has a resistance of 6 Ω and an inductive reactance of 8 Ω. Calculate the impedance of the circuit.", a: "10 Ω", options: ["2 Ω", "7 Ω", "10 Ω", "14 Ω"]},
  {q: "The half-life of a radioactive substance is 5 days. After 20 days, what percentage of the original activity remains?", a: "6.25%", options: ["25%", "12.5%", "6.25%", "3.125%"]},
  {q: "Calculate the force of attraction between two masses of 10 kg and 20 kg kept 2 m apart. [G = 6.67 × 10⁻¹¹ Nm²kg⁻²]", a: "3.34 × 10⁻⁹ N", options: ["1.67 × 10⁻⁹ N", "3.34 × 10⁻⁹ N", "6.67 × 10⁻⁹ N", "1.33 × 10⁻⁸ N"]},
  {q: "A simple pendulum of length 1.6 m has a period T. If the length is reduced to 0.4 m, the new period will be", a: "0.5T", options: ["0.25T", "0.5T", "2T", "4T"]},
  {q: "A bullet of mass 0.05 kg moving at 200 ms⁻¹ hits a wooden block and penetrates 0.1 m before stopping. Calculate the average resistive force.", a: "10,000 N", options: ["5,000 N", "10,000 N", "20,000 N", "40,000 N"]},
  {q: "An engine develops 10 kW of power while pulling a load at a constant velocity of 50 ms⁻¹. Calculate the tractive force.", a: "200 N", options: ["200 N", "500 N", "1000 N", "5000 N"]},
  {q: "Calculate the escape velocity from a planet with mass 6.0 × 10²⁴ kg and radius 6.4 × 10⁶ m. [G = 6.67 × 10⁻¹¹ Nm²kg⁻²]", a: "11,183 ms⁻¹", options: ["7,900 ms⁻¹", "11,183 ms⁻¹", "15,500 ms⁻¹", "22,000 ms⁻¹"]},
  {q: "A gas at 27 °C is heated at constant pressure until its volume is doubled. Calculate the final temperature.", a: "327 °C", options: ["54 °C", "300 °C", "327 °C", "600 °C"]},
  {q: "A light of wavelength 500 nm falls on a metal with a work function of 2.0 eV. Calculate the maximum kinetic energy of the photoelectrons. [h = 6.6 × 10⁻³⁴ Js, 1eV = 1.6 × 10⁻¹⁹ J]", a: "0.48 eV", options: ["0.24 eV", "0.48 eV", "0.96 eV", "2.48 eV"]},
  {q: "A stone is dropped from a cliff 80 m high. Calculate its velocity just before it hits the ground. [g = 10 ms⁻²]", a: "40 ms⁻¹", options: ["20 ms⁻¹", "40 ms⁻¹", "60 ms⁻¹", "80 ms⁻¹"]},
  {q: "A transformer with 100% efficiency has 500 primary turns and 10 turns in the secondary. If the primary current is 0.2 A, calculate the secondary current.", a: "10 A", options: ["0.004 A", "2 A", "10 A", "20 A"]},
  {q: "Two capacitors of 3 μF and 6 μF are connected in series. Calculate their effective capacitance.", a: "2 μF", options: ["2 μF", "4.5 μF", "9 μF", "18 μF"]},
  {q: "Calculate the tension in a string of length 2 m and mass 0.01 kg if the fundamental frequency of vibration is 100 Hz.", a: "800 N", options: ["200 N", "400 N", "800 N", "1600 N"]},
  {q: "A 12 V battery is connected to a 4 Ω resistor and a 2 Ω resistor in series. Calculate the power dissipated in the 4 Ω resistor.", a: "16 W", options: ["8 W", "12 W", "16 W", "24 W"]},
  {q: "The efficiency of a machine is 60%. If it requires an effort of 50 N to lift a load of 150 N, calculate the velocity ratio.", a: "5.0", options: ["2.5", "3.0", "5.0", "7.5"]},
  {q: "A steel rod of length 2.0 m increases in length by 1.2 mm when heated from 20 °C to 70 °C. Calculate the linear expansivity.", a: "1.2 × 10⁻⁵ K⁻¹", options: ["1.2 × 10⁻⁵ K⁻¹", "2.4 × 10⁻⁵ K⁻¹", "4.8 × 10⁻⁵ K⁻¹", "6.0 × 10⁻⁶ K⁻¹"]},
  {q: "Calculate the pressure 20 m below the surface of a lake. [Density of water = 1000 kgm⁻³, Atmospheric pressure = 1.01 × 10⁵ Pa, g = 10 ms⁻²]", a: "3.01 × 10⁵ Pa", options: ["1.01 × 10⁵ Pa", "2.00 × 10⁵ Pa", "3.01 × 10⁵ Pa", "4.01 × 10⁵ Pa"]},
  {q: "An alpha particle (mass 6.6 × 10⁻²⁷ kg) moves at 2.0 × 10⁶ ms⁻¹. Calculate its de Broglie wavelength. [h = 6.6 × 10⁻³⁴ Js]", a: "5.0 × 10⁻¹⁴ m", options: ["5.0 × 10⁻¹⁴ m", "1.0 × 10⁻¹³ m", "3.3 × 10⁻¹⁴ m", "6.6 × 10⁻¹³ m"]},
  {q: "A sound wave travels at 340 ms⁻¹. Calculate the distance of a cliff if an echo is heard 2 seconds after a sound is made.", a: "340 m", options: ["170 m", "340 m", "680 m", "1360 m"]},
  {q: "Calculate the torque of a 50 N force acting perpendicularly at the end of a 0.2 m wrench.", a: "10 Nm", options: ["5 Nm", "10 Nm", "25 Nm", "50 Nm"]},
  {q: "A 2 kg mass is attached to a spring (k = 200 Nm⁻¹). Calculate the frequency of oscillation.", a: "1.59 Hz", options: ["0.80 Hz", "1.59 Hz", "3.18 Hz", "10.0 Hz"]},
  {q: "If the current in a heater is doubled, by what factor does the heat produced per second increase?", a: "4", options: ["2", "3", "4", "8"]},
  /* --- Specific Latent Heat --- */
  {q: "Calculate the heat required to completely melt 0.5 kg of ice at 0 °C. [Specific latent heat of fusion of ice = 3.36 × 10⁵ Jkg⁻¹]", a: "1.68 × 10⁵ J", options: ["1.68 × 10⁴ J", "3.36 × 10⁵ J", "1.68 × 10⁵ J", "6.72 × 10⁵ J"]},
  {q: "How much energy is released when 10g of steam at 100 °C condenses to water at 100 °C? [Specific latent heat of vaporization = 2.26 × 10⁶ Jkg⁻¹]", a: "22,600 J", options: ["2,260 J", "11,300 J", "22,600 J", "45,200 J"]},
  {q: "Calculate the mass of ice at 0 °C that would be melted by 21,000 J of heat. [Specific latent heat of fusion = 3.36 × 10⁵ Jkg⁻¹]", a: "0.0625 kg", options: ["0.0125 kg", "0.0500 kg", "0.0625 kg", "0.1250 kg"]},
  {q: "A 2.0 kW boiler contains 5.0 kg of water at 100 °C. Calculate the time it takes to turn 1.5 kg of the water into steam. [Specific latent heat of vaporization = 2.26 × 10⁶ Jkg⁻¹]", a: "1695 s", options: ["847 s", "1130 s", "1695 s", "3390 s"]},
  {q: "A refrigerator extracts heat from water at 0 °C to form 2 kg of ice at 0 °C in 5 minutes. Calculate the rate of heat extraction. [Specific latent heat of fusion = 3.36 × 10⁵ Jkg⁻¹]", a: "2240 W", options: ["1120 W", "2240 W", "3360 W", "6720 W"]},
  {q: "Which of the following units is derived?", a: "Newton", options: ["Kilogram", "Metre", "Kelvin", "Newton"]},
  {q: "Which of the following dimensions is correct for momentum?", a: "MLT⁻¹", options: ["ML⁻²T⁻²", "ML⁻¹T⁻¹", "ML²T²", "MLT⁻¹"]},
  {q: "The product of the prefixes giga and pico gives", a: "milli", options: ["kilo", "milli", "micro", "mega"]},
  {q: "A body starts moving with a speed of 40 ms⁻¹ and accelerates uniformly to 90 ms⁻¹ in 4.0 s. Calculate the distance travelled.", a: "260 m", options: ["100 m", "260 m", "200 m", "180 m"]},
  {q: "The angle at which a projectile must be fired to cover maximum range is", a: "45°", options: ["30°", "45°", "60°", "90°"]},
  {q: "A piece of paper soiled with oil becomes", a: "translucent", options: ["transparent", "opaque", "luminous", "translucent"]},
  {q: "Which of the following measuring devices would give the most accurate readings for the thickness of a metal sheet?", a: "Micrometer screw gauge", options: ["Vernier caliper", "Micrometer screw gauge", "Tape rule", "Metre rule"]},
  {q: "An annular eclipse occurs when the", a: "tip of the umbra fails to touch the earth", options: ["Earth comes between the moon and the sun", "penumbra area is greater than the umbra", "tip of the umbra fails to touch the earth", "umbra area is greater than the penumbra"]},
  {q: "A metal bar of length 1.0 m and uniform cross-sectional area of 1.0 × 10⁻⁵ m², extends by 1.5 mm when a force of 200 N is applied. Calculate the Young's modulus of the metal.", a: "1.3 × 10¹⁰ Nm⁻²", options: ["1.3 × 10⁷ Nm⁻²", "2.0 × 10⁷ Nm⁻²", "1.3 × 10¹⁰ Nm⁻²", "2.0 × 10¹⁰ Nm⁻²"]},
  {q: "A stone is thrown vertically upwards with a velocity 40.0 ms⁻¹. Calculate the maximum height reached. [g = 10 ms⁻²]", a: "80.0 m", options: ["320.0 m", "160.0 m", "80.0 m", "40.0 m"]},
  {q: "Two forces of magnitudes 30 N and 40 N act at an angle of 90° to each other. Calculate the magnitude of their resultant.", a: "50.0 N", options: ["10.0 N", "20.0 N", "35.0 N", "50.0 N"]},
  {q: "Which of the following thermometers is most suitable for measuring rapidly changing temperature?", a: "Thermocouple", options: ["Constant volume", "Platinum resistance", "Pyrometer", "Thermocouple"]},
  {q: "The absolute zero degree of temperature is equivalent to", a: "-273 °C", options: ["273 K", "-273 °C", "373 K", "-373 °C"]},
  {q: "Calculate the critical angle of a medium of refractive index 1.60.", a: "38.7°", options: ["58.0°", "51.3°", "38.7°", "32.0°"]},
  {q: "The ratio of the speed of light in vacuum to the speed in a transparent medium is called", a: "index of refraction", options: ["critical angle", "threshold speed", "index of refraction", "internal reflection"]},
  {q: "A virtual image cannot be seen on a screen because it is formed by the", a: "apparent intersection of emergent rays", options: ["actual intersection", "apparent intersection", "actual incident", "apparent incident"]},
  {q: "Which of the following thermometers can be used to measure temperature above 2000 °C?", a: "Pyrometer", options: ["Thermocouple", "Resistance thermometer", "Gas thermometer", "Pyrometer"]},
  {q: "The change in direction of motion of light on moving from one medium to another is known as", a: "refraction", options: ["reflection", "diffraction", "refraction", "interference"]},
  {q: "Which of the following dimensions represents impulse?", a: "MLT⁻¹", options: ["MLT⁻²", "MLT⁻¹", "MLT", "ML"]},
  {q: "A speed of 72 kmh⁻¹ is equivalent to", a: "20 ms⁻¹", options: ["60 ms⁻¹", "30 ms⁻¹", "20 ms⁻¹", "10 ms⁻¹"]},
  {q: "What type of motion is generally performed by the molecules of a liquid in a container?", a: "random", options: ["circular", "random", "rectilinear", "rotational"]},
  {q: "The image formed on a screen is always", a: "inverted", options: ["virtual", "upright", "magnified", "inverted"]},
  {q: "Which of the following units represent Young's modulus of elasticity?", a: "kgm⁻¹s⁻²", options: ["kgm⁻²s⁻²", "kgm⁻³s⁻²", "kgm⁻¹s⁻¹", "kgm⁻¹s⁻²"]},
  {q: "The fundamental SI units in mechanics are", a: "kilogram, metre, second", options: ["dyne, metre, second", "gram, cm, second", "kilogram, metre, second", "newton, metre, second"]},
  {q: "Which instrument is used to determine the steam point of a newly constructed thermometer?", a: "Hypsometer", options: ["Hydrometer", "Hypsometer", "Manometer", "Pyrometer"]},
  {q: "Which of the following physical quantities is a vector?", a: "Magnetic flux density", options: ["Electric potential", "Magnetic flux density", "Luminous intensity", "Kinetic energy"]},
  {q: "A body of mass 2 kg is acted upon by a constant force of 10 N for 3 seconds. Calculate the change in momentum.", a: "30 kg m/s", options: ["15 kg m/s", "20 kg m/s", "30 kg m/s", "60 kg m/s"]},
  {q: "A simple pendulum has a period of 2.0 s. Calculate its length. [g = 10 m/s², π = 3.14]", a: "1.01 m", options: ["0.25 m", "0.50 m", "1.01 m", "2.02 m"]},
  {q: "The property of a body to remain at rest or continue in uniform motion is called", a: "inertia", options: ["momentum", "inertia", "friction", "impulse"]},
  {q: "A machine with an efficiency of 80% is used to lift a load of 400 N through 2 m. Calculate the work done by the machine.", a: "1000 J", options: ["320 J", "500 J", "800 J", "1000 J"]},
  {q: "Which of the following statements about the clinical thermometer is correct?", a: "It has a constriction", options: ["It has a wide bore", "It has a constriction", "Used for furnace", "Range 0°C to 100°C"]},
  {q: "The clinical thermometer is usually sterilized by", a: "wiping with methylated spirit", options: ["boiling", "wiping with methylated spirit", "dipping in ice", "placing over flame"]},
  {q: "Which phenomena is evidence of the particle nature of light?", a: "Photoelectric effect", options: ["Refraction", "Diffraction", "Interference", "Photoelectric effect"]},
  {q: "The number of images formed by two plane mirrors inclined at 60° is", a: "5", options: ["3", "4", "5", "6"]},
  {q: "The power of a lens is 2.5 dioptres. Calculate its focal length.", a: "40.0 cm", options: ["10.0 cm", "25.0 cm", "40.0 cm", "50.0 cm"]},
  {q: "A sound wave of frequency 440 Hz travels at 330 m/s. Calculate its wavelength.", a: "0.75 m", options: ["0.75 m", "1.33 m", "1.50 m", "3.00 m"]},
  {q: "The pitch of a sound note depends on its", a: "frequency", options: ["amplitude", "frequency", "harmonics", "intensity"]},
  {q: "Which factor affects the capacitance of a parallel-plate capacitor?", a: "Area of the plates", options: ["Material of plates", "Area of the plates", "Potential difference", "Charge on plates"]},
  {q: "An electric bulb is rated 60 W, 240 V. Calculate its resistance.", a: "960 Ω", options: ["4 Ω", "60 Ω", "240 Ω", "960 Ω"]},
  {q: "Which of the following properties of a wave remains constant as it moves from one medium to another?", a: "Frequency", options: ["Amplitude", "Wavelength", "Frequency", "Speed"]},
  {q: "The phenomenon where an external force vibrates a body at its natural frequency is called", a: "Resonance", options: ["Damping", "Resonance", "Reverberation", "Diffraction"]},
  {q: "Calculate the work done when a force of 20 N stretches a spring by 50 mm.", a: "0.5 J", options: ["0.1 J", "0.5 J", "1.0 J", "2.5 J"]},
  {q: "The heat required to change the state of a substance at constant temperature is called", a: "Latent heat", options: ["Specific heat capacity", "Heat capacity", "Latent heat", "Molar heat"]},
  {q: "Which of the following is a scalar quantity?", a: "Electric potential", options: ["Force", "Electric potential", "Momentum", "Acceleration"]},
  {q: "The resistance of a wire depends on the following EXCEPT", a: "Mass of the wire", options: ["Length", "Cross-sectional area", "Temperature", "Mass of the wire"]},
  {q: "An electric kettle rated 2.0 kW, 240 V is used for 5 minutes. Calculate the energy consumed.", a: "600 kJ", options: ["10 kJ", "12 kJ", "600 kJ", "720 kJ"]},
  {q: "The charge stored in a capacitor of 5 μF connected to a 12 V battery is", a: "60 μC", options: ["2.4 μC", "17 μC", "60 μC", "72 μC"]},
  {q: "Which of the following particles is the charge carrier in a semiconductor?", a: "Electrons and holes", options: ["Electrons only", "Protons only", "Electrons and holes", "Neutrons"]},
  {q: "The unit of magnetic flux density is", a: "Tesla", options: ["Weber", "Tesla", "Henry", "Farad"]},
  {q: "Which of the following radiations has the highest ionizing power?", a: "Alpha particles", options: ["Alpha particles", "Beta particles", "Gamma rays", "X-rays"]},
  {q: "In a nuclear reactor, the purpose of the control rods is to", a: "Absorb neutrons", options: ["Cool the reactor", "Absorb neutrons", "Speed up protons", "Reflect gamma rays"]},
  {q: "The process by which electrons are emitted from a heated metal surface is called", a: "Thermionic emission", options: ["Photoelectric effect", "Thermionic emission", "Field emission", "Secondary emission"]},
  {q: "A radioactive substance has a half-life of 4 days. What fraction remains after 12 days?", a: "1/8", options: ["1/2", "1/4", "1/6", "1/8"]},
  {q: "The energy of a photon of frequency f is given by", a: "hf", options: ["hf", "h/f", "f/h", "h²f"]},
  {q: "Which of the following is an application of the Doppler effect?", a: "Radar speed guns", options: ["X-ray imaging", "Radar speed guns", "Microscopy", "Nuclear fission"]},
  {q: "A transformer has 500 turns in the primary and 2500 turns in the secondary. If the primary voltage is 220 V, the secondary voltage is", a: "1100 V", options: ["44 V", "110 V", "550 V", "1100 V"]},
  {q: "The force between two point charges is inversely proportional to the", a: "Square of the distance between them", options: ["Distance", "Square of the distance", "Product of charges", "Permittivity"]},
  {q: "Which of the following is used to measure current in a circuit?", a: "Ammeter", options: ["Voltmeter", "Ammeter", "Galvanometer", "Wattmeter"]},
  {q: "The power dissipated in a resistor of 10 Ω when a current of 2 A flows through it is", a: "40 W", options: ["20 W", "40 W", "100 W", "200 W"]},
  {q: "Which of the following units is the correct SI unit for luminous intensity?", a: "candela", options: ["ampere", "candela", "kelvin", "mole"]},
  {q: "A body of mass 5 kg is moving with a velocity of 10 ms⁻¹. Calculate its kinetic energy.", a: "250 J", options: ["50 J", "100 J", "250 J", "500 J"]},
  {q: "The rate of change of momentum is directly proportional to the applied force. This is Newton's", a: "second law of motion", options: ["first law", "second law", "third law", "law of gravitation"]},
  {q: "Calculate the work done in lifting a 50 kg bag of cement through a vertical height of 10 m. [g = 10 ms⁻²]", a: "5000 J", options: ["50 J", "500 J", "5000 J", "10000 J"]},
  {q: "The temperature at which water vapour in the air is just sufficient to saturate it is", a: "dew point", options: ["boiling point", "critical temperature", "dew point", "ice point"]},
  {q: "Which of the following is NOT a fundamental quantity?", a: "Force", options: ["Length", "Mass", "Time", "Force"]},
  {q: "An object is placed 15 cm in front of a convex mirror of focal length 10 cm. Calculate the image distance.", a: "6.0 cm", options: ["6.0 cm", "10.0 cm", "15.0 cm", "30.0 cm"]},
  {q: "The velocity of light in a medium is 2.0 × 10⁸ ms⁻¹. If the speed in vacuum is 3.0 × 10⁸ ms⁻¹, the refractive index is", a: "1.50", options: ["0.67", "1.25", "1.50", "1.67"]},
  {q: "The escape velocity of a rocket from the earth's surface depends on the", a: "radius of the earth", options: ["mass of rocket", "radius of the earth", "speed of rocket", "direction"]},
  {q: "Which of the following is a characteristic of a stationary wave?", a: "Nodes and antinodes are formed", options: ["Energy is transferred", "Nodes and antinodes are formed", "The wave travels with speed of light", "It occurs only in a vacuum"]},
  {q: "The change in the direction of a wave as it passes from one medium to another is", a: "refraction", options: ["reflection", "refraction", "diffraction", "polarization"]},
  {q: "A string is 2.0 m long and has a mass of 0.04 kg. If it is under a tension of 100 N, calculate the speed of a transverse wave in the string.", a: "70.7 ms⁻¹", options: ["50.0 ms⁻¹", "70.7 ms⁻¹", "100.0 ms⁻¹", "200.0 ms⁻¹"]},
  {q: "Which of the following instruments is used to compare the relative densities of two liquids?", a: "Hare's apparatus", options: ["Hydrometer", "Hare's apparatus", "Manometer", "Hygrometer"]},
  {q: "The principle of operation of a pinhole camera is the", a: "rectilinear propagation of light", options: ["refraction of light", "rectilinear propagation of light", "diffraction of light", "dispersion of light"]},
  {q: "A person can see near objects clearly but cannot focus on distant objects. This defect is", a: "myopia", options: ["myopia", "hypermetropia", "presbyopia", "astigmatism"]},
  {q: "The sound note produced by a vibrating string is richer in harmonics than that from an open pipe because", a: "it has more overtones", options: ["it has a higher pitch", "it has more overtones", "it travels faster", "the string is longer"]},
  {q: "Which of the following types of waves cannot be polarized?", a: "Sound waves", options: ["Radio waves", "Light waves", "X-rays", "Sound waves"]},
  {q: "A capacitor of 10 μF is charged to a potential of 200 V. Calculate the energy stored.", a: "0.2 J", options: ["0.1 J", "0.2 J", "2.0 J", "4.0 J"]},
  {q: "The direction of the magnetic field around a straight current-carrying conductor is given by", a: "Maxwell's right-hand grip rule", options: ["Fleming's left-hand rule", "Fleming's right-hand rule", "Maxwell's right-hand grip rule", "Lenz's law"]},
  {q: "In an A.C. circuit, the ratio of the root-mean-square (r.m.s) voltage to the peak voltage is", a: "1/√2", options: ["1/2", "1/√2", "√2", "2"]},
  {q: "Which of the following logic gates gives an output of 1 only when all inputs are 1?", a: "AND gate", options: ["OR gate", "AND gate", "NAND gate", "NOR gate"]},
  {q: "The half-life of a radioactive element is 20 minutes. What fraction of the original sample will decay in 1 hour?", a: "7/8", options: ["1/8", "1/4", "3/4", "7/8"]},
  {q: "The main purpose of a rectifier is to", a: "convert A.C. to D.C.", options: ["amplify signals", "convert A.C. to D.C.", "limit current", "store charge"]},
  {q: "Which of the following particles has the same mass as an electron but opposite charge?", a: "Positron", options: ["Proton", "Neutron", "Positron", "Alpha particle"]},
  {q: "The energy level of an atom is -13.6 eV. If an electron transitions to a level of -3.4 eV, calculate the energy absorbed.", a: "10.2 eV", options: ["3.4 eV", "10.2 eV", "13.6 eV", "17.0 eV"]},
  {q: "A hydraulic press has a small piston of area 0.01 m² and a large piston of area 0.05 m². If a force of 100 N is applied to the small piston, the force on the large piston is", a: "500 N", options: ["20 N", "100 N", "250 N", "500 N"]},
  {q: "Which of the following is an example of a simple harmonic motion?", a: "Motion of a simple pendulum", options: ["A car moving on a curve", "Motion of a simple pendulum", "A bird flying", "A spinning top"]},
  {q: "The coefficient of static friction depends on the", a: "nature of the surfaces in contact", options: ["area of surfaces", "nature of the surfaces in contact", "weight of the body", "velocity of the body"]},
  {q: "The pressure in a fluid at a given depth is independent of the", a: "shape of the container", options: ["density of fluid", "acceleration due to gravity", "shape of the container", "depth"]},
  {q: "Which of the following radiations is used in the treatment of cancer?", a: "Gamma rays", options: ["Infrared", "Ultraviolet", "Gamma rays", "Radio waves"]},
  {q: "A step-down transformer has a primary voltage of 2400 V and a secondary voltage of 120 V. The turns ratio is", a: "20:1", options: ["1:20", "20:1", "10:1", "1:10"]},
  {q: "The process by which a heavy nucleus splits into two lighter nuclei is", a: "nuclear fission", options: ["nuclear fusion", "radioactivity", "nuclear fission", "ionization"]},
  {q: "Calculate the frequency of a photon whose energy is 6.6 × 10⁻¹⁹ J. [h = 6.6 × 10⁻³⁴ Js]", a: "1.0 × 10¹⁵ Hz", options: ["1.0 × 10¹⁴ Hz", "1.0 × 10¹⁵ Hz", "6.6 × 10¹⁴ Hz", "6.6 × 10¹⁵ Hz"]},
  {q: "The speed of light in a certain medium is 1.5 × 10⁸ ms⁻¹. Calculate the refractive index. [c = 3.0 × 10⁸ ms⁻¹]", a: "2.0", options: ["0.5", "1.5", "2.0", "3.0"]},
  {q: "Which of the following is a non-renewable source of energy?", a: "Petroleum", options: ["Wind", "Solar", "Petroleum", "Tides"]},
  {q: "The property of water which makes it suitable as a coolant in car engines is its", a: "high specific heat capacity", options: ["low density", "high specific heat capacity", "low boiling point", "transparency"]},
  {q: "A metal of mass 0.5 kg at 100 °C is dropped into 1.0 kg of water at 20 °C. The final temperature is", a: "24 °C", options: ["22 °C", "24 °C", "26 °C", "28 °C"]},
  {q: "The phenomenon of surface tension is due to", a: "cohesion between liquid molecules", options: ["adhesion", "cohesion between liquid molecules", "viscosity", "evaporation"]},
  {q: "Which of the following is used to detect infra-red radiation?", a: "Thermopile", options: ["Photometer", "Thermopile", "Spectrometer", "Geiger counter"]},
  {q: "The particle emitted during beta decay is a/an", a: "electron", options: ["proton", "neutron", "electron", "helium nucleus"]},
  {q: "The time taken for the activity of a radioactive sample to reduce to half its initial value is", a: "half-life", options: ["mean life", "decay constant", "half-life", "period"]},
  {q: "Which of the following is a vector quantity?", a: "Weight", options: ["Mass", "Weight", "Volume", "Density"]},
  {q: "Calculate the momentum of a 0.1 kg ball moving at 20 ms⁻¹.", a: "2.0 kg ms⁻¹", options: ["0.2 kg ms⁻¹", "2.0 kg ms⁻¹", "20 kg ms⁻¹", "200 kg ms⁻¹"]},
  {q: "A force of 50 N acts on a body for 0.1 s. Calculate the impulse.", a: "5.0 Ns", options: ["0.5 Ns", "5.0 Ns", "50 Ns", "500 Ns"]},
  {q: "The unit of electric field intensity is", a: "NC⁻¹", options: ["JC⁻¹", "NC⁻¹", "Vm", "Am⁻¹"]},
  {q: "A wire of length 2.0 m has a resistance of 10 Ω. If the length is doubled, the new resistance is", a: "20 Ω", options: ["5 Ω", "10 Ω", "20 Ω", "40 Ω"]},
  {q: "The component that allows current to flow in only one direction is a", a: "diode", options: ["resistor", "capacitor", "diode", "inductor"]},
  {q: "Which of the following is used to store electric charges?", a: "Capacitor", options: ["Resistor", "Inductor", "Capacitor", "Switch"]},
  {q: "The power of a machine that does 600 J of work in 10 s is", a: "60 W", options: ["6 W", "60 W", "600 W", "6000 W"]},
  {q: "Which radiation has the least penetrating power?", a: "Alpha particles", options: ["Alpha particles", "Beta particles", "Gamma rays", "X-rays"]},
  {q: "The frequency of an A.C. source in Nigeria is", a: "50 Hz", options: ["50 Hz", "60 Hz", "100 Hz", "220 Hz"]},
  {q: "Calculate the work done by a 100 W bulb in 1 minute.", a: "6000 J", options: ["100 J", "600 J", "3600 J", "6000 J"]},
  {q: "The boiling point of water on the Fahrenheit scale is", a: "212 °F", options: ["32 °F", "100 °F", "180 °F", "212 °F"]},
 {q: "Which of the following materials is a good conductor of electricity?", a: "Graphite", options: ["Plastic", "Wood", "Glass", "Graphite"]},
  {q: "A transformer has 100 turns in primary and 400 turns in secondary. If input is 12 V, the output is", a: "48 V", options: ["3 V", "12 V", "48 V", "400 V"]},
  {q: "Emission of electrons from metal when light of sufficient frequency shines on it is", a: "photoelectric effect", options: ["thermionic emission", "photoelectric effect", "field emission", "secondary emission"]},
  {q: "Count rate falls from 400 cps to 50 cps in 9 hours. Calculate the half-life.", a: "3 hours", options: ["2 hours", "3 hours", "4.5 hours", "6 hours"]},
  {q: "Which of the following radiations is electromagnetic in nature?", a: "X-rays", options: ["Alpha rays", "Beta rays", "Cathode rays", "X-rays"]},
  {q: "The process of joining two light nuclei to form a heavier nucleus is called", a: "nuclear fusion", options: ["nuclear fission", "nuclear fusion", "radioactivity", "ionization"]},
  {q: "Calculate the pressure exerted by a man of mass 80 kg standing on a floor of area 0.4 m². [g = 10 ms⁻²]", a: "2000 Nm⁻²", options: ["200 Nm⁻²", "400 Nm⁻²", "2000 Nm⁻²", "3200 Nm⁻²"]},
  {q: "Which of the following describes a material that can be drawn into thin wires?", a: "Ductile", options: ["Brittle", "Malleable", "Ductile", "Elastic"]},
  {q: "The energy stored in a stretched string of force constant k and extension e is", a: "½ke²", options: ["ke", "ke²", "½ke", "½ke²"]},
  {q: "A simple machine with a velocity ratio of 5 requires an effort of 100 N to lift a 400 N load. Efficiency is", a: "80%", options: ["20%", "40%", "80%", "100%"]},
  {q: "The linear expansivity of a metal is 2.0 × 10⁻⁵ K⁻¹. Calculate its area expansivity.", a: "4.0 × 10⁻⁵ K⁻¹", options: ["1.0 × 10⁻⁵ K⁻¹", "2.0 × 10⁻⁵ K⁻¹", "4.0 × 10⁻⁵ K⁻¹", "8.0 × 10⁻⁵ K⁻¹"]},
  {q: "The SI unit of magnetic induction is", a: "Tesla", options: ["Weber", "Tesla", "Henry", "Farad"]}
 ],
}